// Code generated by "stringer -type TargetName"; DO NOT EDIT.

package builtin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Passwords-0]
	_ = x[APIKeysAndTokens-1]
}

const _TargetName_name = "PasswordsAPIKeysAndTokens"

var _TargetName_index = [...]uint8{0, 9, 25}

func (i TargetName) String() string {
	if i < 0 || i >= TargetName(len(_TargetName_index)-1) {
		return "TargetName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TargetName_name[_TargetName_index[i]:_TargetName_index[i+1]]
}
