// Code generated by "stringer -type Provider"; DO NOT EDIT.

package source

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Local-0]
	_ = x[Github-1]
}

const _Provider_name = "LocalGithub"

var _Provider_index = [...]uint8{0, 5, 11}

func (i Provider) String() string {
	if i < 0 || i >= Provider(len(_Provider_index)-1) {
		return "Provider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Provider_name[_Provider_index[i]:_Provider_index[i+1]]
}
