// Code generated by "stringer -type DiffOperation"; DO NOT EDIT.

package git

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Equal-0]
	_ = x[Delete-1]
	_ = x[Add-2]
}

const _DiffOperation_name = "EqualDeleteAdd"

var _DiffOperation_index = [...]uint8{0, 5, 11, 14}

func (i DiffOperation) String() string {
	if i < 0 || i >= DiffOperation(len(_DiffOperation_index)-1) {
		return "DiffOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DiffOperation_name[_DiffOperation_index[i]:_DiffOperation_index[i+1]]
}
